### ISSUE TITLE
Highlight modified text in the code

### ISSUE THREAD

**Issue by mattbel10** [milikhin/seabass2#137]
**Is your feature request related to a problem? Please describe.**
When I add or modify or delete text in the code, I need to have the possibility to see it highlighted somehow, even after closing the app and reopening it, to be always aware of the modifIcations I made some time ago.

**Describe the solution you'd like**
A different row background color would make the trick, if any possible.

**Comment by milikhin** [comment]
Thank you for the feature request! That would be nice to have, although would require:

- some work to probably integrate Seabass with git to detect changes
- highlighting detected changes within the UI

I like how VSCode implements the feature, it could probably be used as a good example for UI.
Anyway, due to the large amount of work required, I won't work on the feature myself. But if anybody would like to contribute the feature, pull requests are welcome! :-)
