### ISSUE TITLE
Copy to clipboard not implemented?

### ISSUE THREAD

**Issue by Pohli** [milikhin/seabass2#32]
I don't know how to copy selected text to clipboard. It's not done automatically by selecting text but it works like this in other apps.

Jolla Phone with SFOS 3.0.1.11 and Seabass 0.3.1

**Comment by milikhin** [comment]
Copying text is not currently implemented on Sailfish OS with on screen keyboard.
I think selected text isn't copied automatically is because the editor component handles selections internally, so Sailfish OS is unaware of the text selections.

Copying text works though with hardware keyboards using Ctrl+C shortcut.
