### ISSUE TITLE
Rendering issue with Erlang

### ISSUE THREAD

**Issue by attah** [milikhin/seabass2#7]
In Erlang, format strings use ~ similar to how C uses %.
For whatever reason, sequences like  `~p` render like ` ~  p  `.
Attaching a small example. Extension should be .erl, but GitHub refuses.
[test.erl.txt](https://github.com/milikhin/seabass2/files/4604459/test.erl.txt)

**Comment by milikhin** [comment]
Thank you for the code sample.

The issue seems to exist upstream in Ace. I can reproduce it using the [Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html). So a proper fix is required for Ace. I've created a bug report with your example: ajaxorg/ace#4290

As for the Seabass I'll implement a quick and dirty fix :-)
